# --------------------------------------------------------------------------------
# Autogenerated by Altair One content definition compiler.
# Do not modify this file.
# --------------------------------------------------------------------------------
# definitions

from .CustomerCreateCustomer import *
from .CustomerDeleteCustomer import *
from .CustomerGetCustomer import *
from .CustomerGetAllCustomers import *
from .CustomerFilterCustomers import *
from .CustomerSearchCustomer import *
from .CustomerUpdateCustomer import *
from .CustomerGetCustomerOrders import *
from .CustomerCreateCustomerFiles import *
from .CustomerGetCustomerFiles import *
from .CustomerCreateCustomerCustomFiles import *
