// --------------------------------------------------------------------------------
// stubs for action ItemGetAll generated by Altair One content definition compiler.
// ItemGetAllPre  [optional] precheck and setup resources required for action.
// ItemGetAllRun  business logic of action and set outputs.
// ItemGetAllPost [optional] postchecks and free resources aquired by action.
// *** DO NOT MODIFY STUB DEFINITIONS ***.
// --------------------------------------------------------------------------------
//Created from JsActionSrcTemplate
/**
 * @typedef {import("../../apis/js/altair/crm1/ItemActions/ItemGetAll").ItemGetAllInputs} ItemGetAllInputs
 * @typedef {import("../../apis/js/altair/crm1/ItemActions/ItemGetAll").ItemGetAllOutputs} ItemGetAllOutputs
 * @typedef {import("@altair/system").ActionContext} ActionContext
 */


/**
 * Implement business logic of action and set outputs
 * 
 * @param { ItemGetAllInputs} inputs action inputs
 * @param { ItemGetAllOutputs} outputs action outputs
 * @param {ActionContext} context action context
 */
async function  ItemGetAllRun(inputs, outputs, context){

     const Search = require("@altair/system").Search;
     const session = context.session;
     const response = await Search.search({
          session,
          filter: 'system.contentType is @contentType',
          bindVars: {
             contentType: "altair.crm1.Item"
          }
     });
     outputs.items = response.entities;

}


module.exports = {
     ItemGetAllRun}