# --------------------------------------------------------------------------------
# stubs for action ItemGetAllItems generated by Altair One content definition compiler.
# ItemGetAllItemsPre  [optional] precheck and setup resources required for action.
# ItemGetAllItemsRun  business logic of action and set outputs.
# ItemGetAllItemsPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext,Search
from altair.crm5 import ItemGetAllItemsInputs
from altair.crm5 import ItemGetAllItemsOutputs


async def ItemGetAllItemsRun(inputs: ItemGetAllItemsInputs, outputs: ItemGetAllItemsOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (ItemGetAllItemsInputs): action inputs
        outputs (ItemGetAllItemsOutputs): action outputs
        context (ActionContext): action context
    '''
    session = context.session;
    response = await Search.search(
          session=session,
          filter= 'system.contentType is @contentType',
          bindVars= {
             "contentType": "altair.crm5.Item"
          }
     )
    outputs.items = response.entities;

