# --------------------------------------------------------------------------------
# stubs for action ItemCreatePy generated by Altair One content definition compiler.
# ItemCreatePyPre  [optional] precheck and setup resources required for action.
# ItemCreatePyRun  business logic of action and set outputs.
# ItemCreatePyPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext
from altair.crm1 import ItemCreatePyInputs
from altair.crm1 import ItemCreatePyOutputs
from altair.system import Content

async def ItemCreatePyRun(inputs: ItemCreatePyInputs, outputs: ItemCreatePyOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (ItemCreatePyInputs): action inputs
        outputs (ItemCreatePyOutputs): action outputs
        context (ActionContext): action context
    '''
    content = await Content.create(session=context.session, contentType= "altair.crm2.Item", data= inputs);
    outputs.itemRef = content;

