// --------------------------------------------------------------------------------
// stubs for action ItemUpdateItem generated by Altair One content definition compiler.
// ItemUpdateItemPre  [optional] precheck and setup resources required for action.
// ItemUpdateItemRun  business logic of action and set outputs.
// ItemUpdateItemPost [optional] postchecks and free resources aquired by action.
// *** DO NOT MODIFY STUB DEFINITIONS ***.
// --------------------------------------------------------------------------------
//Created from JsActionSrcTemplate
/**
 * @typedef {import("../../apis/js/altair/crm1/ItemActions/ItemUpdateItem").ItemUpdateItemInputs} ItemUpdateItemInputs
 * @typedef {import("../../apis/js/altair/crm1/ItemActions/ItemUpdateItem").ItemUpdateItemOutputs} ItemUpdateItemOutputs
 * @typedef {import("@altair/system").ActionContext} ActionContext
 */


/**
 * Implement business logic of action and set outputs
 * 
 * @param { ItemUpdateItemInputs} inputs action inputs
 * @param { ItemUpdateItemOutputs} outputs action outputs
 * @param {ActionContext} context action context
 */
async function  ItemUpdateItemRun(inputs, outputs, context){
}


module.exports = {
     ItemUpdateItemRun}