# --------------------------------------------------------------------------------
# stubs for action ItemGetItem generated by Altair One content definition compiler.
# ItemGetItemPre  [optional] precheck and setup resources required for action.
# ItemGetItemRun  business logic of action and set outputs.
# ItemGetItemPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext,Content,ContentRef
from altair.crm5 import ItemGetItemInputs
from altair.crm5 import ItemGetItemOutputs


async def ItemGetItemRun(inputs: ItemGetItemInputs, outputs: ItemGetItemOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (ItemGetItemInputs): action inputs
        outputs (ItemGetItemOutputs): action outputs
        context (ActionContext): action context
    '''
    testRef = ContentRef(session=context.session)
    testRef.id = inputs.id
    testRef.contentType = "altair.crm5.Item"
    getByRefOutputs = await Content.getByRef(contentRef=testRef, session=context.session)
    outputs.itemRef = getByRefOutputs.content

