# --------------------------------------------------------------------------------
# stubs for action ItemFilterItems generated by Altair One content definition compiler.
# ItemFilterItemsPre  [optional] precheck and setup resources required for action.
# ItemFilterItemsRun  business logic of action and set outputs.
# ItemFilterItemsPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext,Search
from altair.crm5 import ItemFilterItemsInputs
from altair.crm5 import ItemFilterItemsOutputs


async def ItemFilterItemsRun(inputs: ItemFilterItemsInputs, outputs: ItemFilterItemsOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (ItemFilterItemsInputs): action inputs
        outputs (ItemFilterItemsOutputs): action outputs
        context (ActionContext): action context
    '''
    filterVal = 'name like "'+inputs.name + \
        '" && system.contentType in ["altair.crm5.Item"]'
    print("filterVal :", filterVal)
    
    sortField = inputs.paginationObj['sortBy']
    sortDirection = inputs.paginationObj['sortDir']
    pageLimit = inputs.paginationObj['limit']
    pageOffset = inputs.paginationObj['offset']
    
    result = await Search.search(session=context.session,
                                 filter=filterVal,
                                 sort=[{
                                     "field": sortField,
                                     "direction": sortDirection
                                 }],
                                 pagination={
                                     "limit": pageLimit,
                                     "offset": pageOffset,
                                 },
                                 searchOptions={
                                     "returnCounts":True
                                 }
                                 )
    outputs.items = result.entities
    outputs.totalItemsCount = result.count

