# --------------------------------------------------------------------------------
# stubs for action ItemDeletePy generated by Altair One content definition compiler.
# ItemDeletePyPre  [optional] precheck and setup resources required for action.
# ItemDeletePyRun  business logic of action and set outputs.
# ItemDeletePyPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext,Content
from altair.crm1 import ItemDeletePyInputs
from altair.crm1 import ItemDeletePyOutputs


async def ItemDeletePyRun(inputs: ItemDeletePyInputs, outputs: ItemDeletePyOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (ItemDeletePyInputs): action inputs
        outputs (ItemDeletePyOutputs): action outputs
        context (ActionContext): action context
    '''
    output = await Content.findByAttributes(session= context.session,
           contentType= "altair.crm2.Item",
           data= {"_key": inputs.id}
     )
    content1 = output.contents[0];
    await content1.delete();
    outputs.status = "Item deleted";

