# --------------------------------------------------------------------------------
# stubs for action ItemCreateItem generated by Altair One content definition compiler.
# ItemCreateItemPre  [optional] precheck and setup resources required for action.
# ItemCreateItemRun  business logic of action and set outputs.
# ItemCreateItemPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext,Content
from altair.crm5 import ItemCreateItemInputs
from altair.crm5 import ItemCreateItemOutputs


async def ItemCreateItemRun(inputs: ItemCreateItemInputs, outputs: ItemCreateItemOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (ItemCreateItemInputs): action inputs
        outputs (ItemCreateItemOutputs): action outputs
        context (ActionContext): action context
    '''
    content = await Content.create(session=context.session, contentType= "altair.crm5.Item", data= inputs);
    outputs.itemRef = content;

