# --------------------------------------------------------------------------------
# stubs for action ItemGetAllPy generated by Altair One content definition compiler.
# ItemGetAllPyPre  [optional] precheck and setup resources required for action.
# ItemGetAllPyRun  business logic of action and set outputs.
# ItemGetAllPyPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext,Search
from altair.crm1 import ItemGetAllPyInputs
from altair.crm1 import ItemGetAllPyOutputs


async def ItemGetAllPyRun(inputs: ItemGetAllPyInputs, outputs: ItemGetAllPyOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (ItemGetAllPyInputs): action inputs
        outputs (ItemGetAllPyOutputs): action outputs
        context (ActionContext): action context
    '''
    session = context.session;
    response = await Search.search(
          session=session,
          filter= 'system.contentType is @contentType',
          bindVars= {
             "contentType": "altair.crm2.Item"
          }
     )
    outputs.items = response.entities;

