// --------------------------------------------------------------------------------
// stubs for action ItemCreateItem generated by Altair One content definition compiler.
// ItemCreateItemPre  [optional] precheck and setup resources required for action.
// ItemCreateItemRun  business logic of action and set outputs.
// ItemCreateItemPost [optional] postchecks and free resources aquired by action.
// *** DO NOT MODIFY STUB DEFINITIONS ***.
// --------------------------------------------------------------------------------
//Created from JsActionSrcTemplate
/**
 * @typedef {import("../../apis/js/altair/crm1/ItemActions/ItemCreateItem").ItemCreateItemInputs} ItemCreateItemInputs
 * @typedef {import("../../apis/js/altair/crm1/ItemActions/ItemCreateItem").ItemCreateItemOutputs} ItemCreateItemOutputs
 * @typedef {import("@altair/system").ActionContext} ActionContext
 */


/**
 * Implement business logic of action and set outputs
 * 
 * @param { ItemCreateItemInputs} inputs action inputs
 * @param { ItemCreateItemOutputs} outputs action outputs
 * @param {ActionContext} context action context
 */
async function  ItemCreateItemRun(inputs, outputs, context){

     const Content = require("@altair/system").Content;
     var session = context.session;
     var {content} = await Content.create({session, contentType: "altair.crm1.Item", data: inputs});
     outputs.itemRef = content;

}

module.exports = {
     ItemCreateItemRun}