# --------------------------------------------------------------------------------
# stubs for action CustomerGetCustomerFiles generated by Altair One content definition compiler.
# CustomerGetCustomerFilesPre  [optional] precheck and setup resources required for action.
# CustomerGetCustomerFilesRun  business logic of action and set outputs.
# CustomerGetCustomerFilesPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext,Content
from altair.crm5 import CustomerGetCustomerFilesInputs
from altair.crm5 import CustomerGetCustomerFilesOutputs


async def CustomerGetCustomerFilesRun(inputs: CustomerGetCustomerFilesInputs, outputs: CustomerGetCustomerFilesOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (CustomerGetCustomerFilesInputs): action inputs
        outputs (CustomerGetCustomerFilesOutputs): action outputs
        context (ActionContext): action context
    '''
    customerRef = await Content.getByRef(session=context.session,contentRef=inputs.customerRef)
    files=await customerRef.content.getRelatedContents(direction="OUT", relationNames=['customer_files'])
    outputs.files=files

    