# --------------------------------------------------------------------------------
# stubs for action CustomerGetCustomerOrders generated by Altair One content definition compiler.
# CustomerGetCustomerOrdersPre  [optional] precheck and setup resources required for action.
# CustomerGetCustomerOrdersRun  business logic of action and set outputs.
# CustomerGetCustomerOrdersPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext,Content,ActionExecOptions
from altair.crm5 import CustomerGetCustomerOrdersInputs
from altair.crm5 import CustomerGetCustomerOrdersOutputs,Order


async def CustomerGetCustomerOrdersRun(inputs: CustomerGetCustomerOrdersInputs, outputs: CustomerGetCustomerOrdersOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (CustomerGetCustomerOrdersInputs): action inputs
        outputs (CustomerGetCustomerOrdersOutputs): action outputs
        context (ActionContext): action context
    '''
    output = await Content.findByAttributes(
        session=context.session,
        contentType='altair.crm5.Customer',
        data={"_key": inputs.id}
    )
    val = output.contents[0]
    
    # here we are getting the orders data  based on the  customer 
    rels = await val.getRelations(direction="IN", relationNames=["order_customer"])
    orders = await val.getRelatedContents(direction="IN", relationNames=["order_customer"])
    
    print(orders)
    outputs.orders = orders
    
    
