# --------------------------------------------------------------------------------
# stubs for action CustomerGetCustomer generated by Altair One content definition compiler.
# CustomerGetCustomerPre  [optional] precheck and setup resources required for action.
# CustomerGetCustomerRun  business logic of action and set outputs.
# CustomerGetCustomerPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext
from altair.crm5 import CustomerGetCustomerInputs
from altair.crm5 import CustomerGetCustomerOutputs
from altair.system.Content import Content,ContentRef


async def CustomerGetCustomerRun(inputs: CustomerGetCustomerInputs, outputs: CustomerGetCustomerOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (CustomerGetCustomerInputs): action inputs
        outputs (CustomerGetCustomerOutputs): action outputs
        context (ActionContext): action context
    '''
    try:
        # output = await Content.findByAttributes(
        #     session=context.session,
        #     contentType='altair.crm1.Customer',
        #     data={"_key": inputs.id}
        # )
        # outputs.customer = output.contents[0]
        
        
    
        testRef = ContentRef(session=context.session)
        testRef.id = inputs.id
        testRef.contentType = "altair.crm5.Customer"
        getByRefOutputs = await Content.getByRef(contentRef=testRef, session=context.session)
        outputs.customerRef = getByRefOutputs.content

        
    except Exception as e:
        import traceback
        print(e)
        print(traceback.format_exc())

