// --------------------------------------------------------------------------------
// stubs for action CustomerDeleteCustomer generated by Altair One content definition compiler.
// CustomerDeleteCustomerPre  [optional] precheck and setup resources required for action.
// CustomerDeleteCustomerRun  business logic of action and set outputs.
// CustomerDeleteCustomerPost [optional] postchecks and free resources aquired by action.
// *** DO NOT MODIFY STUB DEFINITIONS ***.
// --------------------------------------------------------------------------------
//Created from JsActionSrcTemplate
/**
 * @typedef {import("../../apis/js/altair/crm1/CustomerActions/CustomerDeleteCustomer").CustomerDeleteCustomerInputs} CustomerDeleteCustomerInputs
 * @typedef {import("../../apis/js/altair/crm1/CustomerActions/CustomerDeleteCustomer").CustomerDeleteCustomerOutputs} CustomerDeleteCustomerOutputs
 * @typedef {import("@altair/system").ActionContext} ActionContext
 */


/**
 * Implement business logic of action and set outputs
 * 
 * @param { CustomerDeleteCustomerInputs} inputs action inputs
 * @param { CustomerDeleteCustomerOutputs} outputs action outputs
 * @param {ActionContext} context action context
 */
async function  CustomerDeleteCustomerRun(inputs, outputs, context){
     
     const Content = require("@altair/system").Content;
     const session = context.session;
     const output = await Content.findByAttributes({session: session,
           contentType: "altair.crm1.Customer",
           data: {_key: inputs.id}
     });
     content1 = output.get('contents')[0];
     await content1.delete();
     outputs.status = "Customer deleted";
     
}


module.exports = {
     CustomerDeleteCustomerRun}