# --------------------------------------------------------------------------------
# stubs for action CustomerCreateCustomer generated by Altair One content definition compiler.
# CustomerCreateCustomerPre  [optional] precheck and setup resources required for action.
# CustomerCreateCustomerRun  business logic of action and set outputs.
# CustomerCreateCustomerPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext,Content
from altair.crm5 import CustomerCreateCustomerInputs
from altair.crm5 import CustomerCreateCustomerOutputs,Customer


async def CustomerCreateCustomerRun(inputs: CustomerCreateCustomerInputs, outputs: CustomerCreateCustomerOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (CustomerCreateCustomerInputs): action inputs
        outputs (CustomerCreateCustomerOutputs): action outputs
        context (ActionContext): action context
    '''
    # session = context.session;
    # content = await Content.create(session=session, contentType= "altair.crm5.Customer", data= inputs);
    # outputs.customerRef = content;
    
    customer = Customer(session=context.session)
    
    # Update the attributes
    customer.name = inputs.name
    customer.email = inputs.email
    customer.imageId = inputs.imageId
    await context.session.save()
    
    outputs.customerRef = customer


