# --------------------------------------------------------------------------------
# stubs for action CustomerGetAllCustomers generated by Altair One content definition compiler.
# CustomerGetAllCustomersPre  [optional] precheck and setup resources required for action.
# CustomerGetAllCustomersRun  business logic of action and set outputs.
# CustomerGetAllCustomersPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext,Search
from altair.crm5 import CustomerGetAllCustomersInputs
from altair.crm5 import CustomerGetAllCustomersOutputs


async def CustomerGetAllCustomersRun(inputs: CustomerGetAllCustomersInputs, outputs: CustomerGetAllCustomersOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (CustomerGetAllCustomersInputs): action inputs
        outputs (CustomerGetAllCustomersOutputs): action outputs
        context (ActionContext): action context
    '''
    result = await Search.search(session=context.session,filter='system.contentType in ["altair.crm5.Customer"]')
    outputs.customers = result.entities

