# --------------------------------------------------------------------------------
# stubs for action CustomerGetAllPy generated by Altair One content definition compiler.
# CustomerGetAllPyPre  [optional] precheck and setup resources required for action.
# CustomerGetAllPyRun  business logic of action and set outputs.
# CustomerGetAllPyPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext
from altair.crm1 import CustomerGetAllPyInputs
from altair.crm1 import CustomerGetAllPyOutputs
from altair.system import Search


async def CustomerGetAllPyRun(inputs: CustomerGetAllPyInputs, outputs: CustomerGetAllPyOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (CustomerGetAllPyInputs): action inputs
        outputs (CustomerGetAllPyOutputs): action outputs
        context (ActionContext): action context
    '''
    result = await Search.search(session=context.session,filter='system.contentType in ["altair.crm2.Customer"]')
    outputs.customers = result.entities

