// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------

const pack = {

        // definitions
         ...require('./ItemUpdateItem'),
         ...require('./ItemCreateItem'),
         ...require('./ItemDeleteItem'),
         ...require('./ItemGetAllItems'),
         ...require('./ItemGetItem'),
         ...require('./ItemFilterItems'),
         ...require('./ItemGetItemOrders'),
         ...require('./ItemGetItemCustomers')
}


module.exports = pack;