// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class ItemCreateItem extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new ItemCreateItemInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.ItemCreateItem'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Item/createItem'
    }

}

/**
 * Class for inputs of action ItemCreateItem
 * 
 */
class ItemCreateItemInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.ItemCreateItemInputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get name(){
        return this.get('name')
    }
    
    set name(value){
        this.set('name', value)
    }
    /**
     * String arg
     * 
     * @type { float }
     */
    get cost(){
        return this.get('cost')
    }
    
    set cost(value){
        this.set('cost', value)
    }
}

/**
 * Class for outputs of action ItemCreateItem
 * 
 */
class ItemCreateItemOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.ItemCreateItemOutputs'
    }

    /**
     * String arg
     * 
     * @type { ItemRef }
     */
    get itemRef(){
        return this.get('itemRef')
    }
    
    set itemRef(value){
        this.set('itemRef', value)
    }
}

Factory.register('altair.crm5.ItemCreateItem', ItemCreateItem)
Factory.register('altair.crm5.ItemCreateItemInputs', ItemCreateItemInputs)
Factory.register('altair.crm5.ItemCreateItemOutputs', ItemCreateItemOutputs)

module.exports = {
    ItemCreateItem,
    ItemCreateItemInputs,
    ItemCreateItemOutputs
}