// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class ItemGetItemOrders extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new ItemGetItemOrdersInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.ItemGetItemOrders'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Item/getItemOrders'
    }

}

/**
 * Class for inputs of action ItemGetItemOrders
 * 
 */
class ItemGetItemOrdersInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.ItemGetItemOrdersInputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get id(){
        return this.get('id')
    }
    
    set id(value){
        this.set('id', value)
    }
}

/**
 * Class for outputs of action ItemGetItemOrders
 * 
 */
class ItemGetItemOrdersOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.ItemGetItemOrdersOutputs'
    }

    /**
     * String arg
     * 
     * @type { list }
     */
    get orders(){
        return this.get('orders')
    }
    
    set orders(value){
        this.set('orders', value)
    }
}

Factory.register('altair.crm5.ItemGetItemOrders', ItemGetItemOrders)
Factory.register('altair.crm5.ItemGetItemOrdersInputs', ItemGetItemOrdersInputs)
Factory.register('altair.crm5.ItemGetItemOrdersOutputs', ItemGetItemOrdersOutputs)

module.exports = {
    ItemGetItemOrders,
    ItemGetItemOrdersInputs,
    ItemGetItemOrdersOutputs
}