// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class ItemDeleteItem extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new ItemDeleteItemInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.ItemDeleteItem'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Item/deleteItem'
    }

}

/**
 * Class for inputs of action ItemDeleteItem
 * 
 */
class ItemDeleteItemInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.ItemDeleteItemInputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get id(){
        return this.get('id')
    }
    
    set id(value){
        this.set('id', value)
    }
}

/**
 * Class for outputs of action ItemDeleteItem
 * 
 */
class ItemDeleteItemOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.ItemDeleteItemOutputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get status(){
        return this.get('status')
    }
    
    set status(value){
        this.set('status', value)
    }
}

Factory.register('altair.crm5.ItemDeleteItem', ItemDeleteItem)
Factory.register('altair.crm5.ItemDeleteItemInputs', ItemDeleteItemInputs)
Factory.register('altair.crm5.ItemDeleteItemOutputs', ItemDeleteItemOutputs)

module.exports = {
    ItemDeleteItem,
    ItemDeleteItemInputs,
    ItemDeleteItemOutputs
}