// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class ItemGetItem extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new ItemGetItemInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.ItemGetItem'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Item/getItem'
    }

}

/**
 * Class for inputs of action ItemGetItem
 * 
 */
class ItemGetItemInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.ItemGetItemInputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get id(){
        return this.get('id')
    }
    
    set id(value){
        this.set('id', value)
    }
}

/**
 * Class for outputs of action ItemGetItem
 * 
 */
class ItemGetItemOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.ItemGetItemOutputs'
    }

    /**
     * String arg
     * 
     * @type { ItemRef }
     */
    get itemRef(){
        return this.get('itemRef')
    }
    
    set itemRef(value){
        this.set('itemRef', value)
    }
}

Factory.register('altair.crm5.ItemGetItem', ItemGetItem)
Factory.register('altair.crm5.ItemGetItemInputs', ItemGetItemInputs)
Factory.register('altair.crm5.ItemGetItemOutputs', ItemGetItemOutputs)

module.exports = {
    ItemGetItem,
    ItemGetItemInputs,
    ItemGetItemOutputs
}