// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class ItemGetItemCustomers extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new ItemGetItemCustomersInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.ItemGetItemCustomers'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Item/getItemCustomers'
    }

}

/**
 * Class for inputs of action ItemGetItemCustomers
 * 
 */
class ItemGetItemCustomersInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.ItemGetItemCustomersInputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get id(){
        return this.get('id')
    }
    
    set id(value){
        this.set('id', value)
    }
}

/**
 * Class for outputs of action ItemGetItemCustomers
 * 
 */
class ItemGetItemCustomersOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.ItemGetItemCustomersOutputs'
    }

    /**
     * String arg
     * 
     * @type { list }
     */
    get customers(){
        return this.get('customers')
    }
    
    set customers(value){
        this.set('customers', value)
    }
}

Factory.register('altair.crm5.ItemGetItemCustomers', ItemGetItemCustomers)
Factory.register('altair.crm5.ItemGetItemCustomersInputs', ItemGetItemCustomersInputs)
Factory.register('altair.crm5.ItemGetItemCustomersOutputs', ItemGetItemCustomersOutputs)

module.exports = {
    ItemGetItemCustomers,
    ItemGetItemCustomersInputs,
    ItemGetItemCustomersOutputs
}