// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class ItemGetAllItems extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new ItemGetAllItemsInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.ItemGetAllItems'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Item/getAllItems'
    }

}

/**
 * Class for inputs of action ItemGetAllItems
 * 
 */
class ItemGetAllItemsInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.ItemGetAllItemsInputs'
    }

}

/**
 * Class for outputs of action ItemGetAllItems
 * 
 */
class ItemGetAllItemsOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.ItemGetAllItemsOutputs'
    }

    /**
     * String arg
     * 
     * @type { list }
     */
    get items(){
        return this.get('items')
    }
    
    set items(value){
        this.set('items', value)
    }
}

Factory.register('altair.crm5.ItemGetAllItems', ItemGetAllItems)
Factory.register('altair.crm5.ItemGetAllItemsInputs', ItemGetAllItemsInputs)
Factory.register('altair.crm5.ItemGetAllItemsOutputs', ItemGetAllItemsOutputs)

module.exports = {
    ItemGetAllItems,
    ItemGetAllItemsInputs,
    ItemGetAllItemsOutputs
}