// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class ItemUpdateItem extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new ItemUpdateItemInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.ItemUpdateItem'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Item/updateItem'
    }

}

/**
 * Class for inputs of action ItemUpdateItem
 * 
 */
class ItemUpdateItemInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.ItemUpdateItemInputs'
    }

    /**
     * String arg
     * 
     * @type { ItemRef }
     */
    get itemRef(){
        return this.get('itemRef')
    }
    
    set itemRef(value){
        this.set('itemRef', value)
    }
}

/**
 * Class for outputs of action ItemUpdateItem
 * 
 */
class ItemUpdateItemOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.ItemUpdateItemOutputs'
    }

    /**
     * String arg
     * 
     * @type { ItemRef }
     */
    get itemRef(){
        return this.get('itemRef')
    }
    
    set itemRef(value){
        this.set('itemRef', value)
    }
}

Factory.register('altair.crm5.ItemUpdateItem', ItemUpdateItem)
Factory.register('altair.crm5.ItemUpdateItemInputs', ItemUpdateItemInputs)
Factory.register('altair.crm5.ItemUpdateItemOutputs', ItemUpdateItemOutputs)

module.exports = {
    ItemUpdateItem,
    ItemUpdateItemInputs,
    ItemUpdateItemOutputs
}