# --------------------------------------------------------------------------------
# stubs for action CustomFileEntityDeleteFile generated by Altair One content definition compiler.
# CustomFileEntityDeleteFilePre  [optional] precheck and setup resources required for action.
# CustomFileEntityDeleteFileRun  business logic of action and set outputs.
# CustomFileEntityDeleteFilePost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext,Content,Fs
from altair.crm5 import CustomFileEntityDeleteFileInputs
from altair.crm5 import CustomFileEntityDeleteFileOutputs


async def CustomFileEntityDeleteFileRun(inputs: CustomFileEntityDeleteFileInputs, outputs: CustomFileEntityDeleteFileOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (CustomFileEntityDeleteFileInputs): action inputs
        outputs (CustomFileEntityDeleteFileOutputs): action outputs
        context (ActionContext): action context
    '''
    try:
        output = await Content.findByAttributes(
            session=context.session,
            contentType="altair.crm5.CustomFileEntity",
            data={"_key": inputs.id}
        )
        customFileEntityRef = output.contents[0]
        
        await Fs.rm(session=context.session,contentRef=output.contents[0].fileRef)
        await customFileEntityRef.delete()
    except Exception as e:
        import traceback
        print(e)
        print(traceback.format_exc())

