# --------------------------------------------------------------------------------
# stubs for action CustomFileEntityCreateFile generated by Altair One content definition compiler.
# CustomFileEntityCreateFilePre  [optional] precheck and setup resources required for action.
# CustomFileEntityCreateFileRun  business logic of action and set outputs.
# CustomFileEntityCreateFilePost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext,Content
from altair.crm5 import CustomFileEntityCreateFileInputs
from altair.crm5 import CustomFileEntityCreateFileOutputs,CustomFileEntity


async def CustomFileEntityCreateFileRun(inputs: CustomFileEntityCreateFileInputs, outputs: CustomFileEntityCreateFileOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (CustomFileEntityCreateFileInputs): action inputs
        outputs (CustomFileEntityCreateFileOutputs): action outputs
        context (ActionContext): action context
    '''
    # customerRef = await Content.getByRef(session=context.session, contentRef=inputs.contentRef)
   
    fileRef = await Content.getByRef(session=context.session, contentRef=inputs.fileRef)
    # await customerRef.content.addCustomer_files(customer_files=fileRef.content)
    
    
    customFileEntity = CustomFileEntity(session=context.session)
    customFileEntity.contentRef = inputs.contentRef
    customFileEntity.description = inputs.description
    customFileEntity.isLock = inputs.islock
    
    await customFileEntity.setCustomFileEntity_files(CustomFileEntity_files=fileRef.content)
    customFileEntity.fileRef= fileRef.content

    await context.session.save()
    
    # output = {
    #     "id":customFileEntity.id,
    #     "description": "",
    #     "islock" : "",
    #     "fileRef":fileRef.content
    # }
    
    outputs.file = customFileEntity
    

