# --------------------------------------------------------------------------------
# Autogenerated by Altair One content definition compiler.
# Do not modify this file.
# --------------------------------------------------------------------------------

#Created from PythonContentEventClassTemplate
from typing import Optional
from typing import Any
from typing import List
from altair.system import Session
from altair.system import ContentUserEvent
from altair.system import Content

import typing
if typing.TYPE_CHECKING:
    from altair.system import ContentUserEvent

class CustomerCreateCustomerEvent(ContentUserEvent):
    def __init__(self, session: Session = None):
        super().__init__(session=session)

    @classmethod
    def New(cls, thisContent: Content, customerRef: 'CustomerRef',  ):
        '''Create new instance of this class

        Args:
            thisContent (Content): instance of Content against which the event will be emitted.
            customerRef (CustomerRef): customer Reference

        Returns:
            altair.crm5.CustomerEvents.CustomerCreateCustomerEvent: Event object
        '''
        
        event = cls(session=thisContent.session)
        event.resource = thisContent.getRef().toString().replace(".", "_")
        

        # set payload
        _payload = {}
        _payload['customerRef'] = customerRef
        event.payload = _payload

        return event

    @property
    def contentType(self) -> str:
        '''Content type

        Returns:
            str: Content type
        '''
        return 'altair.crm5.CustomerCreateCustomerEvent'

