// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------

const pack = {

        // definitions
         ...require('./OrderUpdateOrder'),
         ...require('./OrderCreateOrder'),
         ...require('./OrderGetAllOrders'),
         ...require('./OrderDeleteOrder'),
         ...require('./OrderGetOrder'),
         ...require('./OrderFilterOrders'),
         ...require('./OrderGetOrderItems'),
         ...require('./OrderDeleteOrderItems')
}


module.exports = pack;