// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class OrderFilterOrders extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new OrderFilterOrdersInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.OrderFilterOrders'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Order/filterOrders'
    }

}

/**
 * Class for inputs of action OrderFilterOrders
 * 
 */
class OrderFilterOrdersInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.OrderFilterOrdersInputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get name(){
        return this.get('name')
    }
    
    set name(value){
        this.set('name', value)
    }
    /**
     * String arg
     * 
     * @type { object }
     */
    get paginationObj(){
        return this.get('paginationObj')
    }
    
    set paginationObj(value){
        this.set('paginationObj', value)
    }
}

/**
 * Class for outputs of action OrderFilterOrders
 * 
 */
class OrderFilterOrdersOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.OrderFilterOrdersOutputs'
    }

    /**
     * String arg
     * 
     * @type { object }
     */
    get orders(){
        return this.get('orders')
    }
    
    set orders(value){
        this.set('orders', value)
    }
    /**
     * String arg
     * 
     * @type { float }
     */
    get totalOrdersCount(){
        return this.get('totalOrdersCount')
    }
    
    set totalOrdersCount(value){
        this.set('totalOrdersCount', value)
    }
}

Factory.register('altair.crm5.OrderFilterOrders', OrderFilterOrders)
Factory.register('altair.crm5.OrderFilterOrdersInputs', OrderFilterOrdersInputs)
Factory.register('altair.crm5.OrderFilterOrdersOutputs', OrderFilterOrdersOutputs)

module.exports = {
    OrderFilterOrders,
    OrderFilterOrdersInputs,
    OrderFilterOrdersOutputs
}