// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class OrderUpdateOrder extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new OrderUpdateOrderInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.OrderUpdateOrder'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Order/updateOrder'
    }

}

/**
 * Class for inputs of action OrderUpdateOrder
 * 
 */
class OrderUpdateOrderInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.OrderUpdateOrderInputs'
    }

    /**
     * String arg
     * 
     * @type { OrderRef }
     */
    get orderRef(){
        return this.get('orderRef')
    }
    
    set orderRef(value){
        this.set('orderRef', value)
    }
}

/**
 * Class for outputs of action OrderUpdateOrder
 * 
 */
class OrderUpdateOrderOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.OrderUpdateOrderOutputs'
    }

    /**
     * String arg
     * 
     * @type { OrderRef }
     */
    get orderRef(){
        return this.get('orderRef')
    }
    
    set orderRef(value){
        this.set('orderRef', value)
    }
}

Factory.register('altair.crm5.OrderUpdateOrder', OrderUpdateOrder)
Factory.register('altair.crm5.OrderUpdateOrderInputs', OrderUpdateOrderInputs)
Factory.register('altair.crm5.OrderUpdateOrderOutputs', OrderUpdateOrderOutputs)

module.exports = {
    OrderUpdateOrder,
    OrderUpdateOrderInputs,
    OrderUpdateOrderOutputs
}