# --------------------------------------------------------------------------------
# Autogenerated by Altair One content definition compiler.
# Do not modify this file.
# --------------------------------------------------------------------------------

#Created from PythonGlobalActionClassTemplate

import os
import importlib.util as imp
from altair.system import Session
from altair.system import UserAction
from altair.system import ActionInputs
from altair.system import ActionOutputs
from altair.system import ActionExecOptions
from altair.system import Factory
from more_itertools import first

from typing import Any
from typing import List


class FileUploadFile(UserAction):

    '''Class for action FileUploadFile
    '''
    def __init__(self, session: Session = None):
        super().__init__(session=session)
        self._srcModule = None

        # set inputs
        self.set('inputs', FileUploadFileInputs(session=session))
        self.set('inline', True)

    @property
    def contentType(self) -> str:
        '''Content type

        Returns:
            str: Content type
        '''
        return 'altair.crm5.FileUploadFile'

    @property
    def relativeUrl(self) -> str:
        '''RelativeUrl

        Returns:
            str: Relative Url
        '''
        return '/altair/crm5/File/uploadFile'
    

    def _getSourceModule(self):
        if self._srcModule != None:
            return self._srcModule

        fileDirPath = os.path.dirname(os.path.realpath(__file__))
        srcPath = '{}/../src'.format(fileDirPath)
        if os.path.exists(srcPath) == False:
            srcPath = '{}/../../../../../src'.format(fileDirPath)

        spec = imp.spec_from_file_location('FileUploadFile', srcPath + '/FileActions/FileUploadFile.py')
        self._srcModule = imp.module_from_spec(spec)
        spec.loader.exec_module(self._srcModule)
        return self._srcModule


    async def run(self):
        '''Method to run for action execution
        '''
        # set outputs
        self.set('outputs', FileUploadFileOutputs(session=self.session))

        await self._getSourceModule().FileUploadFileRun(self.inputs, self.outputs, self.context)


class FileUploadFileInputs(ActionInputs):
    '''Class for inputs of action FileUploadFile
    '''
    def __init__(self, session=None):
        super().__init__(session=session)

    @property
    def propertyType(self) -> str:
        '''Property type

        Returns:
            str: Property type
        '''
        return 'altair.crm5.FileUploadFileInputs'

    @property
    def filepath(self) -> 'str':
        '''String arg

        Returns:
            str: String arg
        '''
        return self.get('filepath')

    @filepath.setter
    def filepath(self, value: 'str') -> None:
        '''String arg

        Args:
            value (str): String arg
        '''
        self.set('filepath', value)

    @property
    def name(self) -> 'str':
        '''String arg

        Returns:
            str: String arg
        '''
        return self.get('name')

    @name.setter
    def name(self, value: 'str') -> None:
        '''String arg

        Args:
            value (str): String arg
        '''
        self.set('name', value)


class FileUploadFileOutputs(ActionOutputs):
    '''Class for outputs of action FileUploadFile
    '''
    def __init__(self, session=None):
        super().__init__(session=session)

    def __iter__(self):
        yield from [getattr(self, i) for i in ['fileRef' ]]

    @property
    def propertyType(self) -> str:
        '''Property type

        Returns:
            str: Property type
        '''
        return 'altair.crm5.FileUploadFileOutputs'

    @property
    def fileRef(self) -> 'FileRef':
        '''String arg

        Returns:
            FileRef: arg
        '''
        return self.get('fileRef')

    @fileRef.setter
    def fileRef(self, value: 'FileRef') -> None:
        '''String arg

        Args:
            value (FileRef): arg
        '''
        self.set('fileRef', value)



Factory.register('altair.crm5.FileUploadFile', FileUploadFile)
Factory.register('altair.crm5.FileUploadFileInputs', FileUploadFileInputs)
Factory.register('altair.crm5.FileUploadFileOutputs', FileUploadFileOutputs)

