# --------------------------------------------------------------------------------
# Autogenerated by Altair One content definition compiler.
# Do not modify this file.
# --------------------------------------------------------------------------------

from altair.system import Session
from altair.system import ContentRef
from altair.system import Relation
from altair.system import ActionExecOptions
from altair.system import Content
from .FileActions import FileUploadFile
from .FileActions import FileUploadFileOutputs

from typing import Any
from typing import List
from typing import Union
from typing import Callable
from typing import Optional


class File(Content):
    def __init__(self, session: Session):
        super().__init__(session=session)

    ############# PROPERTIES START ##############

    @property
    def contentType(self):
        '''Content type

        Returns:
            str: Content type
        '''
        return "altair.crm5.File"


    ############## PROPERTIES END ###############

    @staticmethod
    async def uploadFile(session: Session  ,filepath: Optional['str'] = None ,name: Optional['str'] = None , execOptions: ActionExecOptions = None) -> FileUploadFileOutputs:
        '''Inline action

        Args:
            filepath (str): file path
            name (str): name
            execOptions (atlair.system.ActionExecOptions): Action execution options
            session (altair.system.Session): Session for action

        Returns:
            altair.crm5.FileActions.FileUploadFile.FileUploadFileOutputs: Action Outputs
        '''
        # create action and set inputs
        _action = FileUploadFile(session=session)
        _action.inputs.filepath = filepath
        _action.inputs.name = name

        # execute action
        await _action.execute(execOptions)
        return _action.outputs
        



class FileRef(ContentRef):
    '''Reference class for content definition File
    '''
    def __init__(self, session: Session = None):
        super().__init__(session=session)