# --------------------------------------------------------------------------------
# Autogenerated by Altair One content definition compiler.
# Do not modify this file.
# --------------------------------------------------------------------------------
# definitions

from .CustomFileEntityCreateFile import *
from .CustomFileEntityGetFiles import *
from .CustomFileEntityUpdateFile import *
from .CustomFileEntityDeleteFile import *
