# --------------------------------------------------------------------------------
# Autogenerated by Altair One content definition compiler.
# Do not modify this file.
# --------------------------------------------------------------------------------

#Created from PythonGlobalActionClassTemplate

import os
import importlib.util as imp
from altair.system import Session
from altair.system import UserAction
from altair.system import ActionInputs
from altair.system import ActionOutputs
from altair.system import ActionExecOptions
from altair.system import Factory
from more_itertools import first

from typing import Any
from typing import List


class CustomFileEntityCreateFile(UserAction):

    '''Class for action CustomFileEntityCreateFile
    '''
    def __init__(self, session: Session = None):
        super().__init__(session=session)
        self._srcModule = None

        # set inputs
        self.set('inputs', CustomFileEntityCreateFileInputs(session=session))
        self.set('inline', True)

    @property
    def contentType(self) -> str:
        '''Content type

        Returns:
            str: Content type
        '''
        return 'altair.crm5.CustomFileEntityCreateFile'

    @property
    def relativeUrl(self) -> str:
        '''RelativeUrl

        Returns:
            str: Relative Url
        '''
        return '/altair/crm5/CustomFileEntity/createFile'
    

    def _getSourceModule(self):
        if self._srcModule != None:
            return self._srcModule

        fileDirPath = os.path.dirname(os.path.realpath(__file__))
        srcPath = '{}/../src'.format(fileDirPath)
        if os.path.exists(srcPath) == False:
            srcPath = '{}/../../../../../src'.format(fileDirPath)

        spec = imp.spec_from_file_location('CustomFileEntityCreateFile', srcPath + '/CustomFileEntityActions/CustomFileEntityCreateFile.py')
        self._srcModule = imp.module_from_spec(spec)
        spec.loader.exec_module(self._srcModule)
        return self._srcModule


    async def run(self):
        '''Method to run for action execution
        '''
        # set outputs
        self.set('outputs', CustomFileEntityCreateFileOutputs(session=self.session))

        await self._getSourceModule().CustomFileEntityCreateFileRun(self.inputs, self.outputs, self.context)


class CustomFileEntityCreateFileInputs(ActionInputs):
    '''Class for inputs of action CustomFileEntityCreateFile
    '''
    def __init__(self, session=None):
        super().__init__(session=session)

    @property
    def propertyType(self) -> str:
        '''Property type

        Returns:
            str: Property type
        '''
        return 'altair.crm5.CustomFileEntityCreateFileInputs'

    @property
    def contentRef(self) -> 'Any':
        '''String arg

        Returns:
            Any: String arg
        '''
        return self.get('contentRef')

    @contentRef.setter
    def contentRef(self, value: 'Any') -> None:
        '''String arg

        Args:
            value (Any): String arg
        '''
        self.set('contentRef', value)

    @property
    def description(self) -> 'str':
        '''String arg

        Returns:
            str: String arg
        '''
        return self.get('description')

    @description.setter
    def description(self, value: 'str') -> None:
        '''String arg

        Args:
            value (str): String arg
        '''
        self.set('description', value)

    @property
    def islock(self) -> 'bool':
        '''String arg

        Returns:
            bool: String arg
        '''
        return self.get('islock')

    @islock.setter
    def islock(self, value: 'bool') -> None:
        '''String arg

        Args:
            value (bool): String arg
        '''
        self.set('islock', value)

    @property
    def fileRef(self) -> 'FileEntityRef':
        '''String arg

        Returns:
            FileEntityRef: String arg
        '''
        return self.get('fileRef')

    @fileRef.setter
    def fileRef(self, value: 'FileEntityRef') -> None:
        '''String arg

        Args:
            value (FileEntityRef): String arg
        '''
        self.set('fileRef', value)


class CustomFileEntityCreateFileOutputs(ActionOutputs):
    '''Class for outputs of action CustomFileEntityCreateFile
    '''
    def __init__(self, session=None):
        super().__init__(session=session)

    def __iter__(self):
        yield from [getattr(self, i) for i in ['file' ]]

    @property
    def propertyType(self) -> str:
        '''Property type

        Returns:
            str: Property type
        '''
        return 'altair.crm5.CustomFileEntityCreateFileOutputs'

    @property
    def file(self) -> 'Any':
        '''String arg

        Returns:
            Any: arg
        '''
        return self.get('file')

    @file.setter
    def file(self, value: 'Any') -> None:
        '''String arg

        Args:
            value (Any): arg
        '''
        self.set('file', value)



Factory.register('altair.crm5.CustomFileEntityCreateFile', CustomFileEntityCreateFile)
Factory.register('altair.crm5.CustomFileEntityCreateFileInputs', CustomFileEntityCreateFileInputs)
Factory.register('altair.crm5.CustomFileEntityCreateFileOutputs', CustomFileEntityCreateFileOutputs)

