# --------------------------------------------------------------------------------
# Autogenerated by Altair One content definition compiler.
# Do not modify this file.
# --------------------------------------------------------------------------------

#Created from PythonGlobalActionClassTemplate

import os
import importlib.util as imp
from altair.system import Session
from altair.system import UserAction
from altair.system import ActionInputs
from altair.system import ActionOutputs
from altair.system import ActionExecOptions
from altair.system import Factory
from more_itertools import first

from typing import Any
from typing import List


class CustomFileEntityGetFiles(UserAction):

    '''Class for action CustomFileEntityGetFiles
    '''
    def __init__(self, session: Session = None):
        super().__init__(session=session)
        self._srcModule = None

        # set inputs
        self.set('inputs', CustomFileEntityGetFilesInputs(session=session))
        self.set('inline', True)

    @property
    def contentType(self) -> str:
        '''Content type

        Returns:
            str: Content type
        '''
        return 'altair.crm5.CustomFileEntityGetFiles'

    @property
    def relativeUrl(self) -> str:
        '''RelativeUrl

        Returns:
            str: Relative Url
        '''
        return '/altair/crm5/CustomFileEntity/getFiles'
    

    def _getSourceModule(self):
        if self._srcModule != None:
            return self._srcModule

        fileDirPath = os.path.dirname(os.path.realpath(__file__))
        srcPath = '{}/../src'.format(fileDirPath)
        if os.path.exists(srcPath) == False:
            srcPath = '{}/../../../../../src'.format(fileDirPath)

        spec = imp.spec_from_file_location('CustomFileEntityGetFiles', srcPath + '/CustomFileEntityActions/CustomFileEntityGetFiles.py')
        self._srcModule = imp.module_from_spec(spec)
        spec.loader.exec_module(self._srcModule)
        return self._srcModule


    async def run(self):
        '''Method to run for action execution
        '''
        # set outputs
        self.set('outputs', CustomFileEntityGetFilesOutputs(session=self.session))

        await self._getSourceModule().CustomFileEntityGetFilesRun(self.inputs, self.outputs, self.context)


class CustomFileEntityGetFilesInputs(ActionInputs):
    '''Class for inputs of action CustomFileEntityGetFiles
    '''
    def __init__(self, session=None):
        super().__init__(session=session)

    @property
    def propertyType(self) -> str:
        '''Property type

        Returns:
            str: Property type
        '''
        return 'altair.crm5.CustomFileEntityGetFilesInputs'

    @property
    def contentRef(self) -> 'Any':
        '''String arg

        Returns:
            Any: String arg
        '''
        return self.get('contentRef')

    @contentRef.setter
    def contentRef(self, value: 'Any') -> None:
        '''String arg

        Args:
            value (Any): String arg
        '''
        self.set('contentRef', value)


class CustomFileEntityGetFilesOutputs(ActionOutputs):
    '''Class for outputs of action CustomFileEntityGetFiles
    '''
    def __init__(self, session=None):
        super().__init__(session=session)

    def __iter__(self):
        yield from [getattr(self, i) for i in ['files', 'count' ]]

    @property
    def propertyType(self) -> str:
        '''Property type

        Returns:
            str: Property type
        '''
        return 'altair.crm5.CustomFileEntityGetFilesOutputs'

    @property
    def files(self) -> List['object']:
        '''String arg

        Returns:
            List[Any]: arg
        '''
        return self.get('files')

    @files.setter
    def files(self, value: List['object']) -> None:
        '''String arg

        Args:
            value (List[Any]): arg
        '''
        self.set('files', value)

    @property
    def count(self) -> 'float':
        '''String arg

        Returns:
            float: arg
        '''
        return self.get('count')

    @count.setter
    def count(self, value: 'float') -> None:
        '''String arg

        Args:
            value (float): arg
        '''
        self.set('count', value)



Factory.register('altair.crm5.CustomFileEntityGetFiles', CustomFileEntityGetFiles)
Factory.register('altair.crm5.CustomFileEntityGetFilesInputs', CustomFileEntityGetFilesInputs)
Factory.register('altair.crm5.CustomFileEntityGetFilesOutputs', CustomFileEntityGetFilesOutputs)

