// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsCdefTemplate

const Session = require('@altair/system').Session
const ContentRef = require('@altair/system').ContentRef
const ActionExecOptions = require('@altair/system').ActionExecOptions
const Content = require('@altair/system').Content
const FileUploadFile = require('./FileActions').FileUploadFile
const FileUploadFileOutputs = require('./FileActions').FileUploadFileOutputs

class File extends Content{
    
    constructor({session}) {
        super({session})
    }

    // PROPERTIES START

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType() {
        return 'altair.crm5.File'
    }


    // PROPERTIES END

    /**
     * content Inline Action 
     * 
     * @param string inputs.filepath file path
     * @param string inputs.name name
     * @param {altair.system.ActionExecOptions} inputs.execOptions Action execution options
     * @returns { FileUploadFileActionOutputs } Action outputs
     */
    static async uploadFile({session , filepath, name, execOptions}){
        // create action and set inputs
        let _action = new FileUploadFile({session:session})
        _action.inputs.filepath = filepath
        _action.inputs.name = name

        // execute action
        await _action.execute(execOptions)
        return _action.outputs
    }
    


}

/**
 * Reference class for content definition File
 * 
 */
class FileRef extends ContentRef{
    constructor({session}) {
        super({session})
        this.set('contentType', 'altair.crm5.File')
    }
}

module.exports = { File, FileRef }