# --------------------------------------------------------------------------------
# stubs for action OrderDeleteOrder generated by Altair One content definition compiler.
# OrderDeleteOrderPre  [optional] precheck and setup resources required for action.
# OrderDeleteOrderRun  business logic of action and set outputs.
# OrderDeleteOrderPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext,Content
from altair.crm5 import OrderDeleteOrderInputs
from altair.crm5 import OrderDeleteOrderOutputs


async def OrderDeleteOrderRun(inputs: OrderDeleteOrderInputs, outputs: OrderDeleteOrderOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (OrderDeleteOrderInputs): action inputs
        outputs (OrderDeleteOrderOutputs): action outputs
        context (ActionContext): action context
    '''
    output = await Content.findByAttributes(session=context.session,
                                            contentType="altair.crm5.Order",
                                            data={"_key": inputs.id}
                                            )
    content1 = output.get('contents')[0]
    await content1.delete()
    outputs.status = "Order Deleted"

