# --------------------------------------------------------------------------------
# stubs for action OrderGetOrder generated by Altair One content definition compiler.
# OrderGetOrderPre  [optional] precheck and setup resources required for action.
# OrderGetOrderRun  business logic of action and set outputs.
# OrderGetOrderPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext,ContentRef,Content
from altair.crm5 import OrderGetOrderInputs
from altair.crm5 import OrderGetOrderOutputs
from altair.crm5 import Order

async def OrderGetOrderRun(inputs: OrderGetOrderInputs, outputs: OrderGetOrderOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (OrderGetOrderInputs): action inputs
        outputs (OrderGetOrderOutputs): action outputs
        context (ActionContext): action context
    '''
    output = await Content.findByAttributes(
        session=context.session,
        contentType='altair.crm5.Order',
        data={"_key": inputs.id}
    )
    val = output.contents[0]
    
    customer = await val.getOrder_customer()
    results = dict()
    results["order"] = val
    results["customer"] = customer
    outputs.obj = results
    
    

