# --------------------------------------------------------------------------------
# stubs for action OrderGetAllPy generated by Altair One content definition compiler.
# OrderGetAllPyPre  [optional] precheck and setup resources required for action.
# OrderGetAllPyRun  business logic of action and set outputs.
# OrderGetAllPyPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

# Created from PythonActionSrcTemplate

from altair.system import ActionContext, Search
from altair.crm1 import OrderGetAllPyInputs
from altair.crm1 import OrderGetAllPyOutputs


async def OrderGetAllPyRun(inputs: OrderGetAllPyInputs, outputs: OrderGetAllPyOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (OrderGetAllPyInputs): action inputs
        outputs (OrderGetAllPyOutputs): action outputs
        context (ActionContext): action context
    '''
    response = await Search.search(
        session=context.session,
        filter='system.contentType is @contentType',
        bindVars={
            "contentType": "altair.crm2.Order"
        }
    )

    outputs.orders = response.entities
