// --------------------------------------------------------------------------------
// stubs for action OrderUpdateOrder generated by Altair One content definition compiler.
// OrderUpdateOrderPre  [optional] precheck and setup resources required for action.
// OrderUpdateOrderRun  business logic of action and set outputs.
// OrderUpdateOrderPost [optional] postchecks and free resources aquired by action.
// *** DO NOT MODIFY STUB DEFINITIONS ***.
// --------------------------------------------------------------------------------
//Created from JsActionSrcTemplate
/**
 * @typedef {import("../../apis/js/altair/crm1/OrderActions/OrderUpdateOrder").OrderUpdateOrderInputs} OrderUpdateOrderInputs
 * @typedef {import("../../apis/js/altair/crm1/OrderActions/OrderUpdateOrder").OrderUpdateOrderOutputs} OrderUpdateOrderOutputs
 * @typedef {import("@altair/system").ActionContext} ActionContext
 */


/**
 * Implement business logic of action and set outputs
 * 
 * @param { OrderUpdateOrderInputs} inputs action inputs
 * @param { OrderUpdateOrderOutputs} outputs action outputs
 * @param {ActionContext} context action context
 */
async function  OrderUpdateOrderRun(inputs, outputs, context){
}


module.exports = {
     OrderUpdateOrderRun}