// --------------------------------------------------------------------------------
// stubs for action OrderGetOrder generated by Altair One content definition compiler.
// OrderGetOrderPre  [optional] precheck and setup resources required for action.
// OrderGetOrderRun  business logic of action and set outputs.
// OrderGetOrderPost [optional] postchecks and free resources aquired by action.
// *** DO NOT MODIFY STUB DEFINITIONS ***.
// --------------------------------------------------------------------------------
//Created from JsActionSrcTemplate
/**
 * @typedef {import("../../apis/js/altair/crm1/OrderActions/OrderGetOrder").OrderGetOrderInputs} OrderGetOrderInputs
 * @typedef {import("../../apis/js/altair/crm1/OrderActions/OrderGetOrder").OrderGetOrderOutputs} OrderGetOrderOutputs
 * @typedef {import("@altair/system").ActionContext} ActionContext
 */

const { json } = require("stream/consumers");


/**
 * Implement business logic of action and set outputs
 * 
 * @param { OrderGetOrderInputs} inputs action inputs
 * @param { OrderGetOrderOutputs} outputs action outputs
 * @param {ActionContext} context action context
 */
async function  OrderGetOrderRun(inputs, outputs, context){

     const Content = require("@altair/system").Content;
     const ContentRef = require("@altair/system").ContentRef;
     let testRef = new ContentRef({session:context.session})
        testRef.id = inputs.id
        testRef.contentType = "altair.crm1.Order"
     let getByRefOutputs = await Content.getByRef({contentRef:testRef, session:context.session})
     let val = getByRefOutputs.content;

     // Need to get has ticket
     // load relationships
     // by default it is OUT only
     
     let rels = await val.getRelations({direction: "OUT", relationNames: ["order_items"]}); 

     let items = await val.getRelatedContents({direction: "OUT", relationNames: ["order_items"]});	

     outputs.items = items;
     outputs.countJson = (outputs.items).length
     outputs.orderRef = getByRefOutputs.content
     // console.log("content ............................"+JSON.stringify(outputs.items))
     // console.log("content_items ............................"+JSON.stringify(outputs.__refs.items))

}


module.exports = {
     OrderGetOrderRun}