# --------------------------------------------------------------------------------
# stubs for action OrderGetByIdPy generated by Altair One content definition compiler.
# OrderGetByIdPyPre  [optional] precheck and setup resources required for action.
# OrderGetByIdPyRun  business logic of action and set outputs.
# OrderGetByIdPyPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

# Created from PythonActionSrcTemplate

from altair.system import ActionContext, Content, ContentRef
from altair.crm1 import OrderGetByIdPyInputs
from altair.crm1 import OrderGetByIdPyOutputs


async def OrderGetByIdPyRun(inputs: OrderGetByIdPyInputs, outputs: OrderGetByIdPyOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (OrderGetByIdPyInputs): action inputs
        outputs (OrderGetByIdPyOutputs): action outputs
        context (ActionContext): action context
    '''

    testRef = ContentRef(session=context.session)
    testRef.id = inputs.id
    testRef.contentType = "altair.crm2.Order"
    getByRefOutputs = await Content.getByRef(contentRef=testRef, session=context.session)
    val = getByRefOutputs.content

    rels = await val.getRelations(direction="OUT", relationNames=["order_items"])

    items = await val.getRelatedContents(direction="OUT", relationNames=["order_items"])

    outputs.items = items
    outputs.countJson = (outputs.items).length
    outputs.orderRef = getByRefOutputs.content
    print("content is :", outputs.items)
    print("content_items is :", outputs.__refs.items)
