// --------------------------------------------------------------------------------
// stubs for action OrderDeleteOrder generated by Altair One content definition compiler.
// OrderDeleteOrderPre  [optional] precheck and setup resources required for action.
// OrderDeleteOrderRun  business logic of action and set outputs.
// OrderDeleteOrderPost [optional] postchecks and free resources aquired by action.
// *** DO NOT MODIFY STUB DEFINITIONS ***.
// --------------------------------------------------------------------------------
//Created from JsActionSrcTemplate
/**
 * @typedef {import("../../apis/js/altair/crm1/OrderActions/OrderDeleteOrder").OrderDeleteOrderInputs} OrderDeleteOrderInputs
 * @typedef {import("../../apis/js/altair/crm1/OrderActions/OrderDeleteOrder").OrderDeleteOrderOutputs} OrderDeleteOrderOutputs
 * @typedef {import("@altair/system").ActionContext} ActionContext
 */


/**
 * Implement business logic of action and set outputs
 * 
 * @param { OrderDeleteOrderInputs} inputs action inputs
 * @param { OrderDeleteOrderOutputs} outputs action outputs
 * @param {ActionContext} context action context
 */
async function  OrderDeleteOrderRun(inputs, outputs, context){

     const Content = require("@altair/system").Content;
     const session = context.session;
     const output = await Content.findByAttributes({session: session,
           contentType: "altair.crm1.Order",
           data: {_key: inputs.id}
     });
     content1 = output.get('contents')[0];
     await content1.delete();
     outputs.status = "Order Deleted";
}


module.exports = {
     OrderDeleteOrderRun}