# --------------------------------------------------------------------------------
# stubs for action OrderDeleteItem generated by Altair One content definition compiler.
# OrderDeleteItemPre  [optional] precheck and setup resources required for action.
# OrderDeleteItemRun  business logic of action and set outputs.
# OrderDeleteItemPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext,Content
from altair.crm3 import OrderDeleteItemInputs
from altair.crm3 import OrderDeleteItemOutputs


async def OrderDeleteItemRun(inputs: OrderDeleteItemInputs, outputs: OrderDeleteItemOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (OrderDeleteItemInputs): action inputs
        outputs (OrderDeleteItemOutputs): action outputs
        context (ActionContext): action context
    '''
    output = await Content.findByAttributes(session=context.session,
                                            contentType="altair.crm3.Order",
                                            data={"_key": inputs.id}
                                            )
    content1 = output.get('contents')[0]
    await content1.delete()
    outputs.status = "Order Deleted"

