// --------------------------------------------------------------------------------
// stubs for action OrderDeleteAll generated by Altair One content definition compiler.
// OrderDeleteAllPre  [optional] precheck and setup resources required for action.
// OrderDeleteAllRun  business logic of action and set outputs.
// OrderDeleteAllPost [optional] postchecks and free resources aquired by action.
// *** DO NOT MODIFY STUB DEFINITIONS ***.
// --------------------------------------------------------------------------------
//Created from JsActionSrcTemplate
/**
 * @typedef {import("../../apis/js/altair/crm1/OrderActions/OrderDeleteAll").OrderDeleteAllInputs} OrderDeleteAllInputs
 * @typedef {import("../../apis/js/altair/crm1/OrderActions/OrderDeleteAll").OrderDeleteAllOutputs} OrderDeleteAllOutputs
 * @typedef {import("@altair/system").ActionContext} ActionContext
 */


/**
 * Implement business logic of action and set outputs
 * 
 * @param { OrderDeleteAllInputs} inputs action inputs
 * @param { OrderDeleteAllOutputs} outputs action outputs
 * @param {ActionContext} context action context
 */
async function  OrderDeleteAllRun(inputs, outputs, context){

     const Content = require("@altair/system").Content;
     const session = context.session;
     const output = await Content.findByAttributes({session: session,
           contentType: "altair.crm1.Order"});
     content1 = output.get('contents');
     await content1.delete();
     outputs.status = "content1 deleted";
}


module.exports = {
     OrderDeleteAllRun}