# --------------------------------------------------------------------------------
# stubs for action OrderDeleteOrderItems generated by Altair One content definition compiler.
# OrderDeleteOrderItemsPre  [optional] precheck and setup resources required for action.
# OrderDeleteOrderItemsRun  business logic of action and set outputs.
# OrderDeleteOrderItemsPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext,Content,ContentRef
from altair.crm5 import OrderDeleteOrderItemsInputs
from altair.crm5 import OrderDeleteOrderItemsOutputs,Order


async def OrderDeleteOrderItemsRun(inputs: OrderDeleteOrderItemsInputs, outputs: OrderDeleteOrderItemsOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (OrderDeleteOrderItemsInputs): action inputs
        outputs (OrderDeleteOrderItemsOutputs): action outputs
        context (ActionContext): action context
    '''
    output = await Content.findByAttributes(
        session=context.session,
        contentType='altair.crm5.Order',
        data={"_key": inputs.orderId}
    )
    val = output.contents[0]

    testRef = ContentRef(session=context.session)
    testRef.id = inputs.itemId
    testRef.contentType = "altair.crm5.Item"
    getByRefOutputs = await Content.getByRef(contentRef=testRef, session=context.session)

    await val.removeOrder_items(getByRefOutputs.content)


    outputs.status = "Remove Item from Order successfully"

