# --------------------------------------------------------------------------------
# stubs for action OrderDeletePy generated by Altair One content definition compiler.
# OrderDeletePyPre  [optional] precheck and setup resources required for action.
# OrderDeletePyRun  business logic of action and set outputs.
# OrderDeletePyPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

# Created from PythonActionSrcTemplate

from altair.system import ActionContext, Content
from altair.crm1 import OrderDeletePyInputs
from altair.crm1 import OrderDeletePyOutputs


async def OrderDeletePyRun(inputs: OrderDeletePyInputs, outputs: OrderDeletePyOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (OrderDeletePyInputs): action inputs
        outputs (OrderDeletePyOutputs): action outputs
        context (ActionContext): action context
    '''
    output = await Content.findByAttributes(session=context.session,
                                            contentType="altair.crm2.Order",
                                            data={"_key": inputs.id}
                                            )
    content1 = output.get('contents')[0]
    await content1.delete()
    outputs.status = "Order Deleted"
