# --------------------------------------------------------------------------------
# stubs for action OrderGetOrderItems generated by Altair One content definition compiler.
# OrderGetOrderItemsPre  [optional] precheck and setup resources required for action.
# OrderGetOrderItemsRun  business logic of action and set outputs.
# OrderGetOrderItemsPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

# Created from PythonActionSrcTemplate

from altair.system import ActionContext, Content, ContentRef
from altair.crm5 import OrderGetOrderItemsInputs
from altair.crm5 import OrderGetOrderItemsOutputs, Order


async def OrderGetOrderItemsRun(inputs: OrderGetOrderItemsInputs, outputs: OrderGetOrderItemsOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (OrderGetOrderItemsInputs): action inputs
        outputs (OrderGetOrderItemsOutputs): action outputs
        context (ActionContext): action context
    '''
    output = await Content.findByAttributes(
        session=context.session,
        contentType='altair.crm5.Order',
        data={"_key": inputs.id}
    )
    val = output.contents[0]

    # rels = await val.getRelations(direction="OUT", relationNames=["order_items"])
    # items = await val.getRelatedContents(direction="OUT", relationNames=["order_items"])
    
    items = await val.getOrder_items()

    # print("items : ------", items)
    
    outputs.items = items
    