// --------------------------------------------------------------------------------
// stubs for action OrderUpdateOrderPy generated by Altair One content definition compiler.
// OrderUpdateOrderPyPre  [optional] precheck and setup resources required for action.
// OrderUpdateOrderPyRun  business logic of action and set outputs.
// OrderUpdateOrderPyPost [optional] postchecks and free resources aquired by action.
// *** DO NOT MODIFY STUB DEFINITIONS ***.
// --------------------------------------------------------------------------------
//Created from JsActionSrcTemplate
/**
 * @typedef {import("../../apis/js/altair/crm1/OrderActions/OrderUpdateOrderPy").OrderUpdateOrderPyInputs} OrderUpdateOrderPyInputs
 * @typedef {import("../../apis/js/altair/crm1/OrderActions/OrderUpdateOrderPy").OrderUpdateOrderPyOutputs} OrderUpdateOrderPyOutputs
 * @typedef {import("@altair/system").ActionContext} ActionContext
 */


/**
 * Implement business logic of action and set outputs
 * 
 * @param { OrderUpdateOrderPyInputs} inputs action inputs
 * @param { OrderUpdateOrderPyOutputs} outputs action outputs
 * @param {ActionContext} context action context
 */
async function  OrderUpdateOrderPyRun(inputs, outputs, context){
}


module.exports = {
     OrderUpdateOrderPyRun}