# --------------------------------------------------------------------------------
# stubs for action OrderFilterOrderPy generated by Altair One content definition compiler.
# OrderFilterOrderPyPre  [optional] precheck and setup resources required for action.
# OrderFilterOrderPyRun  business logic of action and set outputs.
# OrderFilterOrderPyPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext,Search
from altair.crm1 import OrderFilterOrderPyInputs
from altair.crm1 import OrderFilterOrderPyOutputs


async def OrderFilterOrderPyRun(inputs: OrderFilterOrderPyInputs, outputs: OrderFilterOrderPyOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (OrderFilterOrderPyInputs): action inputs
        outputs (OrderFilterOrderPyOutputs): action outputs
        context (ActionContext): action context
    '''
    print("value is",inputs.name)
    filterVal = 'name like "'+inputs.name+'" && system.contentType in ["altair.crm2.Order"]'
    print("filterVal :",filterVal)
    result = await Search.search(session=context.session, 
                                 filter= filterVal,
                                )
    outputs.orders = result.entities

