# --------------------------------------------------------------------------------
# stubs for action OrderGetAllOrders generated by Altair One content definition compiler.
# OrderGetAllOrdersPre  [optional] precheck and setup resources required for action.
# OrderGetAllOrdersRun  business logic of action and set outputs.
# OrderGetAllOrdersPost [optional] postchecks and free resources aquired by action.
# *** DO NOT MODIFY STUB DEFINITIONS ***.
# --------------------------------------------------------------------------------

#Created from PythonActionSrcTemplate

from altair.system import ActionContext,Search
from altair.crm5 import OrderGetAllOrdersInputs
from altair.crm5 import OrderGetAllOrdersOutputs


async def OrderGetAllOrdersRun(inputs: OrderGetAllOrdersInputs, outputs: OrderGetAllOrdersOutputs, context: ActionContext):
    '''Implement business logic of action and set outputs

    Args:
        inputs (OrderGetAllOrdersInputs): action inputs
        outputs (OrderGetAllOrdersOutputs): action outputs
        context (ActionContext): action context
    '''
    response = await Search.search(
        session=context.session,
        filter='system.contentType is @contentType',
        bindVars={
            "contentType": "altair.crm5.Order"
        }
    )

    outputs.orders = response.entities

