// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------

const pack = {

        // definitions
         ...require('./CustomerCreateCustomerEvent')
}


module.exports = pack;