# --------------------------------------------------------------------------------
# Autogenerated by Altair One content definition compiler.
# Do not modify this file.
# --------------------------------------------------------------------------------

#Created from PythonGlobalActionClassTemplate

import os
import importlib.util as imp
from altair.system import Session
from altair.system import UserAction
from altair.system import ActionInputs
from altair.system import ActionOutputs
from altair.system import ActionExecOptions
from altair.system import Factory
from more_itertools import first

from typing import Any
from typing import List


class OrderCreateOrder(UserAction):

    '''Class for action OrderCreateOrder
    '''
    def __init__(self, session: Session = None):
        super().__init__(session=session)
        self._srcModule = None

        # set inputs
        self.set('inputs', OrderCreateOrderInputs(session=session))
        self.set('inline', True)

    @property
    def contentType(self) -> str:
        '''Content type

        Returns:
            str: Content type
        '''
        return 'altair.crm5.OrderCreateOrder'

    @property
    def relativeUrl(self) -> str:
        '''RelativeUrl

        Returns:
            str: Relative Url
        '''
        return '/altair/crm5/Order/createOrder'
    

    def _getSourceModule(self):
        if self._srcModule != None:
            return self._srcModule

        fileDirPath = os.path.dirname(os.path.realpath(__file__))
        srcPath = '{}/../src'.format(fileDirPath)
        if os.path.exists(srcPath) == False:
            srcPath = '{}/../../../../../src'.format(fileDirPath)

        spec = imp.spec_from_file_location('OrderCreateOrder', srcPath + '/OrderActions/OrderCreateOrder.py')
        self._srcModule = imp.module_from_spec(spec)
        spec.loader.exec_module(self._srcModule)
        return self._srcModule


    async def run(self):
        '''Method to run for action execution
        '''
        # set outputs
        self.set('outputs', OrderCreateOrderOutputs(session=self.session))

        await self._getSourceModule().OrderCreateOrderRun(self.inputs, self.outputs, self.context)


class OrderCreateOrderInputs(ActionInputs):
    '''Class for inputs of action OrderCreateOrder
    '''
    def __init__(self, session=None):
        super().__init__(session=session)

    @property
    def propertyType(self) -> str:
        '''Property type

        Returns:
            str: Property type
        '''
        return 'altair.crm5.OrderCreateOrderInputs'

    @property
    def name(self) -> 'str':
        '''String arg

        Returns:
            str: String arg
        '''
        return self.get('name')

    @name.setter
    def name(self, value: 'str') -> None:
        '''String arg

        Args:
            value (str): String arg
        '''
        self.set('name', value)

    @property
    def contact(self) -> 'str':
        '''String arg

        Returns:
            str: String arg
        '''
        return self.get('contact')

    @contact.setter
    def contact(self, value: 'str') -> None:
        '''String arg

        Args:
            value (str): String arg
        '''
        self.set('contact', value)

    @property
    def address(self) -> 'str':
        '''String arg

        Returns:
            str: String arg
        '''
        return self.get('address')

    @address.setter
    def address(self, value: 'str') -> None:
        '''String arg

        Args:
            value (str): String arg
        '''
        self.set('address', value)

    @property
    def items(self) -> List['ItemRef']:
        '''String arg

        Returns:
            List[ItemRef]: String arg
        '''
        return self.get('items')

    @items.setter
    def items(self, value: List['ItemRef']):
        '''String arg

        Args:
            value (List[ItemRef]): String arg
        '''
        self.set('items', value)

    @property
    def customerRef(self) -> 'CustomerRef':
        '''String arg

        Returns:
            CustomerRef: String arg
        '''
        return self.get('customerRef')

    @customerRef.setter
    def customerRef(self, value: 'CustomerRef') -> None:
        '''String arg

        Args:
            value (CustomerRef): String arg
        '''
        self.set('customerRef', value)


class OrderCreateOrderOutputs(ActionOutputs):
    '''Class for outputs of action OrderCreateOrder
    '''
    def __init__(self, session=None):
        super().__init__(session=session)

    def __iter__(self):
        yield from [getattr(self, i) for i in ['orderRef' ]]

    @property
    def propertyType(self) -> str:
        '''Property type

        Returns:
            str: Property type
        '''
        return 'altair.crm5.OrderCreateOrderOutputs'

    @property
    def orderRef(self) -> 'OrderRef':
        '''String arg

        Returns:
            OrderRef: arg
        '''
        return self.get('orderRef')

    @orderRef.setter
    def orderRef(self, value: 'OrderRef') -> None:
        '''String arg

        Args:
            value (OrderRef): arg
        '''
        self.set('orderRef', value)



Factory.register('altair.crm5.OrderCreateOrder', OrderCreateOrder)
Factory.register('altair.crm5.OrderCreateOrderInputs', OrderCreateOrderInputs)
Factory.register('altair.crm5.OrderCreateOrderOutputs', OrderCreateOrderOutputs)

