# --------------------------------------------------------------------------------
# Autogenerated by Altair One content definition compiler.
# Do not modify this file.
# --------------------------------------------------------------------------------

#Created from PythonGlobalActionClassTemplate

import os
import importlib.util as imp
from altair.system import Session
from altair.system import UserAction
from altair.system import ActionInputs
from altair.system import ActionOutputs
from altair.system import ActionExecOptions
from altair.system import Factory
from more_itertools import first

from typing import Any
from typing import List


class OrderDeleteOrderItems(UserAction):

    '''Class for action OrderDeleteOrderItems
    '''
    def __init__(self, session: Session = None):
        super().__init__(session=session)
        self._srcModule = None

        # set inputs
        self.set('inputs', OrderDeleteOrderItemsInputs(session=session))
        self.set('inline', True)

    @property
    def contentType(self) -> str:
        '''Content type

        Returns:
            str: Content type
        '''
        return 'altair.crm5.OrderDeleteOrderItems'

    @property
    def relativeUrl(self) -> str:
        '''RelativeUrl

        Returns:
            str: Relative Url
        '''
        return '/altair/crm5/Order/deleteOrderItems'
    

    def _getSourceModule(self):
        if self._srcModule != None:
            return self._srcModule

        fileDirPath = os.path.dirname(os.path.realpath(__file__))
        srcPath = '{}/../src'.format(fileDirPath)
        if os.path.exists(srcPath) == False:
            srcPath = '{}/../../../../../src'.format(fileDirPath)

        spec = imp.spec_from_file_location('OrderDeleteOrderItems', srcPath + '/OrderActions/OrderDeleteOrderItems.py')
        self._srcModule = imp.module_from_spec(spec)
        spec.loader.exec_module(self._srcModule)
        return self._srcModule


    async def run(self):
        '''Method to run for action execution
        '''
        # set outputs
        self.set('outputs', OrderDeleteOrderItemsOutputs(session=self.session))

        await self._getSourceModule().OrderDeleteOrderItemsRun(self.inputs, self.outputs, self.context)


class OrderDeleteOrderItemsInputs(ActionInputs):
    '''Class for inputs of action OrderDeleteOrderItems
    '''
    def __init__(self, session=None):
        super().__init__(session=session)

    @property
    def propertyType(self) -> str:
        '''Property type

        Returns:
            str: Property type
        '''
        return 'altair.crm5.OrderDeleteOrderItemsInputs'

    @property
    def orderId(self) -> 'str':
        '''String arg

        Returns:
            str: String arg
        '''
        return self.get('orderId')

    @orderId.setter
    def orderId(self, value: 'str') -> None:
        '''String arg

        Args:
            value (str): String arg
        '''
        self.set('orderId', value)

    @property
    def itemId(self) -> 'str':
        '''String arg

        Returns:
            str: String arg
        '''
        return self.get('itemId')

    @itemId.setter
    def itemId(self, value: 'str') -> None:
        '''String arg

        Args:
            value (str): String arg
        '''
        self.set('itemId', value)


class OrderDeleteOrderItemsOutputs(ActionOutputs):
    '''Class for outputs of action OrderDeleteOrderItems
    '''
    def __init__(self, session=None):
        super().__init__(session=session)

    def __iter__(self):
        yield from [getattr(self, i) for i in ['status' ]]

    @property
    def propertyType(self) -> str:
        '''Property type

        Returns:
            str: Property type
        '''
        return 'altair.crm5.OrderDeleteOrderItemsOutputs'

    @property
    def status(self) -> 'str':
        '''String arg

        Returns:
            str: arg
        '''
        return self.get('status')

    @status.setter
    def status(self, value: 'str') -> None:
        '''String arg

        Args:
            value (str): arg
        '''
        self.set('status', value)



Factory.register('altair.crm5.OrderDeleteOrderItems', OrderDeleteOrderItems)
Factory.register('altair.crm5.OrderDeleteOrderItemsInputs', OrderDeleteOrderItemsInputs)
Factory.register('altair.crm5.OrderDeleteOrderItemsOutputs', OrderDeleteOrderItemsOutputs)

