// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class CustomerCreateCustomerFiles extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new CustomerCreateCustomerFilesInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.CustomerCreateCustomerFiles'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Customer/createCustomerFiles'
    }

}

/**
 * Class for inputs of action CustomerCreateCustomerFiles
 * 
 */
class CustomerCreateCustomerFilesInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerCreateCustomerFilesInputs'
    }

    /**
     * String arg
     * 
     * @type { FileEntityRef }
     */
    get fileRef(){
        return this.get('fileRef')
    }
    
    set fileRef(value){
        this.set('fileRef', value)
    }
    /**
     * String arg
     * 
     * @type { CustomerRef }
     */
    get customerRef(){
        return this.get('customerRef')
    }
    
    set customerRef(value){
        this.set('customerRef', value)
    }
}

/**
 * Class for outputs of action CustomerCreateCustomerFiles
 * 
 */
class CustomerCreateCustomerFilesOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerCreateCustomerFilesOutputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get status(){
        return this.get('status')
    }
    
    set status(value){
        this.set('status', value)
    }
}

Factory.register('altair.crm5.CustomerCreateCustomerFiles', CustomerCreateCustomerFiles)
Factory.register('altair.crm5.CustomerCreateCustomerFilesInputs', CustomerCreateCustomerFilesInputs)
Factory.register('altair.crm5.CustomerCreateCustomerFilesOutputs', CustomerCreateCustomerFilesOutputs)

module.exports = {
    CustomerCreateCustomerFiles,
    CustomerCreateCustomerFilesInputs,
    CustomerCreateCustomerFilesOutputs
}