// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class CustomerGetCustomerOrders extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new CustomerGetCustomerOrdersInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.CustomerGetCustomerOrders'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Customer/getCustomerOrders'
    }

}

/**
 * Class for inputs of action CustomerGetCustomerOrders
 * 
 */
class CustomerGetCustomerOrdersInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerGetCustomerOrdersInputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get id(){
        return this.get('id')
    }
    
    set id(value){
        this.set('id', value)
    }
}

/**
 * Class for outputs of action CustomerGetCustomerOrders
 * 
 */
class CustomerGetCustomerOrdersOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerGetCustomerOrdersOutputs'
    }

    /**
     * String arg
     * 
     * @type { list }
     */
    get orders(){
        return this.get('orders')
    }
    
    set orders(value){
        this.set('orders', value)
    }
}

Factory.register('altair.crm5.CustomerGetCustomerOrders', CustomerGetCustomerOrders)
Factory.register('altair.crm5.CustomerGetCustomerOrdersInputs', CustomerGetCustomerOrdersInputs)
Factory.register('altair.crm5.CustomerGetCustomerOrdersOutputs', CustomerGetCustomerOrdersOutputs)

module.exports = {
    CustomerGetCustomerOrders,
    CustomerGetCustomerOrdersInputs,
    CustomerGetCustomerOrdersOutputs
}