// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class CustomerCreateCustomer extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new CustomerCreateCustomerInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.CustomerCreateCustomer'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Customer/createCustomer'
    }

}

/**
 * Class for inputs of action CustomerCreateCustomer
 * 
 */
class CustomerCreateCustomerInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerCreateCustomerInputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get name(){
        return this.get('name')
    }
    
    set name(value){
        this.set('name', value)
    }
    /**
     * String arg
     * 
     * @type { string }
     */
    get email(){
        return this.get('email')
    }
    
    set email(value){
        this.set('email', value)
    }
    /**
     * String arg
     * 
     * @type { string }
     */
    get imageId(){
        return this.get('imageId')
    }
    
    set imageId(value){
        this.set('imageId', value)
    }
}

/**
 * Class for outputs of action CustomerCreateCustomer
 * 
 */
class CustomerCreateCustomerOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerCreateCustomerOutputs'
    }

    /**
     * String arg
     * 
     * @type { CustomerRef }
     */
    get customerRef(){
        return this.get('customerRef')
    }
    
    set customerRef(value){
        this.set('customerRef', value)
    }
}

Factory.register('altair.crm5.CustomerCreateCustomer', CustomerCreateCustomer)
Factory.register('altair.crm5.CustomerCreateCustomerInputs', CustomerCreateCustomerInputs)
Factory.register('altair.crm5.CustomerCreateCustomerOutputs', CustomerCreateCustomerOutputs)

module.exports = {
    CustomerCreateCustomer,
    CustomerCreateCustomerInputs,
    CustomerCreateCustomerOutputs
}