// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class CustomerUpdateCustomer extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new CustomerUpdateCustomerInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.CustomerUpdateCustomer'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Customer/updateCustomer'
    }

}

/**
 * Class for inputs of action CustomerUpdateCustomer
 * 
 */
class CustomerUpdateCustomerInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerUpdateCustomerInputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get id(){
        return this.get('id')
    }
    
    set id(value){
        this.set('id', value)
    }
    /**
     * String arg
     * 
     * @type { CustomerRef }
     */
    get customer(){
        return this.get('customer')
    }
    
    set customer(value){
        this.set('customer', value)
    }
}

/**
 * Class for outputs of action CustomerUpdateCustomer
 * 
 */
class CustomerUpdateCustomerOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerUpdateCustomerOutputs'
    }

    /**
     * String arg
     * 
     * @type { CustomerRef }
     */
    get customer(){
        return this.get('customer')
    }
    
    set customer(value){
        this.set('customer', value)
    }
}

Factory.register('altair.crm5.CustomerUpdateCustomer', CustomerUpdateCustomer)
Factory.register('altair.crm5.CustomerUpdateCustomerInputs', CustomerUpdateCustomerInputs)
Factory.register('altair.crm5.CustomerUpdateCustomerOutputs', CustomerUpdateCustomerOutputs)

module.exports = {
    CustomerUpdateCustomer,
    CustomerUpdateCustomerInputs,
    CustomerUpdateCustomerOutputs
}