// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class CustomerGetCustomerFiles extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new CustomerGetCustomerFilesInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.CustomerGetCustomerFiles'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Customer/getCustomerFiles'
    }

}

/**
 * Class for inputs of action CustomerGetCustomerFiles
 * 
 */
class CustomerGetCustomerFilesInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerGetCustomerFilesInputs'
    }

    /**
     * String arg
     * 
     * @type { CustomerRef }
     */
    get customerRef(){
        return this.get('customerRef')
    }
    
    set customerRef(value){
        this.set('customerRef', value)
    }
}

/**
 * Class for outputs of action CustomerGetCustomerFiles
 * 
 */
class CustomerGetCustomerFilesOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerGetCustomerFilesOutputs'
    }

    /**
     * String arg
     * 
     * @type { list }
     */
    get files(){
        return this.get('files')
    }
    
    set files(value){
        this.set('files', value)
    }
}

Factory.register('altair.crm5.CustomerGetCustomerFiles', CustomerGetCustomerFiles)
Factory.register('altair.crm5.CustomerGetCustomerFilesInputs', CustomerGetCustomerFilesInputs)
Factory.register('altair.crm5.CustomerGetCustomerFilesOutputs', CustomerGetCustomerFilesOutputs)

module.exports = {
    CustomerGetCustomerFiles,
    CustomerGetCustomerFilesInputs,
    CustomerGetCustomerFilesOutputs
}