// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class CustomerFilterCustomers extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new CustomerFilterCustomersInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.CustomerFilterCustomers'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Customer/filterCustomers'
    }

}

/**
 * Class for inputs of action CustomerFilterCustomers
 * 
 */
class CustomerFilterCustomersInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerFilterCustomersInputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get val(){
        return this.get('val')
    }
    
    set val(value){
        this.set('val', value)
    }
    /**
     * String arg
     * 
     * @type { object }
     */
    get paginationObj(){
        return this.get('paginationObj')
    }
    
    set paginationObj(value){
        this.set('paginationObj', value)
    }
}

/**
 * Class for outputs of action CustomerFilterCustomers
 * 
 */
class CustomerFilterCustomersOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerFilterCustomersOutputs'
    }

    /**
     * String arg
     * 
     * @type { list }
     */
    get customers(){
        return this.get('customers')
    }
    
    set customers(value){
        this.set('customers', value)
    }
    /**
     * String arg
     * 
     * @type { float }
     */
    get totalCustomersCount(){
        return this.get('totalCustomersCount')
    }
    
    set totalCustomersCount(value){
        this.set('totalCustomersCount', value)
    }
}

Factory.register('altair.crm5.CustomerFilterCustomers', CustomerFilterCustomers)
Factory.register('altair.crm5.CustomerFilterCustomersInputs', CustomerFilterCustomersInputs)
Factory.register('altair.crm5.CustomerFilterCustomersOutputs', CustomerFilterCustomersOutputs)

module.exports = {
    CustomerFilterCustomers,
    CustomerFilterCustomersInputs,
    CustomerFilterCustomersOutputs
}