// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class CustomerSearchCustomer extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new CustomerSearchCustomerInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.CustomerSearchCustomer'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Customer/searchCustomer'
    }

}

/**
 * Class for inputs of action CustomerSearchCustomer
 * 
 */
class CustomerSearchCustomerInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerSearchCustomerInputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get name(){
        return this.get('name')
    }
    
    set name(value){
        this.set('name', value)
    }
}

/**
 * Class for outputs of action CustomerSearchCustomer
 * 
 */
class CustomerSearchCustomerOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerSearchCustomerOutputs'
    }

    /**
     * String arg
     * 
     * @type { list }
     */
    get customers(){
        return this.get('customers')
    }
    
    set customers(value){
        this.set('customers', value)
    }
}

Factory.register('altair.crm5.CustomerSearchCustomer', CustomerSearchCustomer)
Factory.register('altair.crm5.CustomerSearchCustomerInputs', CustomerSearchCustomerInputs)
Factory.register('altair.crm5.CustomerSearchCustomerOutputs', CustomerSearchCustomerOutputs)

module.exports = {
    CustomerSearchCustomer,
    CustomerSearchCustomerInputs,
    CustomerSearchCustomerOutputs
}