// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class CustomerCreateCustomerCustomFiles extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new CustomerCreateCustomerCustomFilesInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.CustomerCreateCustomerCustomFiles'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Customer/createCustomerCustomFiles'
    }

}

/**
 * Class for inputs of action CustomerCreateCustomerCustomFiles
 * 
 */
class CustomerCreateCustomerCustomFilesInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerCreateCustomerCustomFilesInputs'
    }

    /**
     * String arg
     * 
     * @type { CustomFileEntityRef }
     */
    get fileObj(){
        return this.get('fileObj')
    }
    
    set fileObj(value){
        this.set('fileObj', value)
    }
}

/**
 * Class for outputs of action CustomerCreateCustomerCustomFiles
 * 
 */
class CustomerCreateCustomerCustomFilesOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerCreateCustomerCustomFilesOutputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get status(){
        return this.get('status')
    }
    
    set status(value){
        this.set('status', value)
    }
}

Factory.register('altair.crm5.CustomerCreateCustomerCustomFiles', CustomerCreateCustomerCustomFiles)
Factory.register('altair.crm5.CustomerCreateCustomerCustomFilesInputs', CustomerCreateCustomerCustomFilesInputs)
Factory.register('altair.crm5.CustomerCreateCustomerCustomFilesOutputs', CustomerCreateCustomerCustomFilesOutputs)

module.exports = {
    CustomerCreateCustomerCustomFiles,
    CustomerCreateCustomerCustomFilesInputs,
    CustomerCreateCustomerCustomFilesOutputs
}