// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class CustomerGetAllCustomers extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new CustomerGetAllCustomersInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.CustomerGetAllCustomers'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Customer/getAllCustomers'
    }

}

/**
 * Class for inputs of action CustomerGetAllCustomers
 * 
 */
class CustomerGetAllCustomersInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerGetAllCustomersInputs'
    }

}

/**
 * Class for outputs of action CustomerGetAllCustomers
 * 
 */
class CustomerGetAllCustomersOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerGetAllCustomersOutputs'
    }

    /**
     * String arg
     * 
     * @type { list }
     */
    get customers(){
        return this.get('customers')
    }
    
    set customers(value){
        this.set('customers', value)
    }
}

Factory.register('altair.crm5.CustomerGetAllCustomers', CustomerGetAllCustomers)
Factory.register('altair.crm5.CustomerGetAllCustomersInputs', CustomerGetAllCustomersInputs)
Factory.register('altair.crm5.CustomerGetAllCustomersOutputs', CustomerGetAllCustomersOutputs)

module.exports = {
    CustomerGetAllCustomers,
    CustomerGetAllCustomersInputs,
    CustomerGetAllCustomersOutputs
}