// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class CustomerGetCustomer extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new CustomerGetCustomerInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.CustomerGetCustomer'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Customer/getCustomer'
    }

}

/**
 * Class for inputs of action CustomerGetCustomer
 * 
 */
class CustomerGetCustomerInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerGetCustomerInputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get id(){
        return this.get('id')
    }
    
    set id(value){
        this.set('id', value)
    }
}

/**
 * Class for outputs of action CustomerGetCustomer
 * 
 */
class CustomerGetCustomerOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerGetCustomerOutputs'
    }

    /**
     * String arg
     * 
     * @type { CustomerRef }
     */
    get customerRef(){
        return this.get('customerRef')
    }
    
    set customerRef(value){
        this.set('customerRef', value)
    }
}

Factory.register('altair.crm5.CustomerGetCustomer', CustomerGetCustomer)
Factory.register('altair.crm5.CustomerGetCustomerInputs', CustomerGetCustomerInputs)
Factory.register('altair.crm5.CustomerGetCustomerOutputs', CustomerGetCustomerOutputs)

module.exports = {
    CustomerGetCustomer,
    CustomerGetCustomerInputs,
    CustomerGetCustomerOutputs
}