// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class CustomerDeleteCustomer extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new CustomerDeleteCustomerInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.CustomerDeleteCustomer'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/Customer/deleteCustomer'
    }

}

/**
 * Class for inputs of action CustomerDeleteCustomer
 * 
 */
class CustomerDeleteCustomerInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerDeleteCustomerInputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get id(){
        return this.get('id')
    }
    
    set id(value){
        this.set('id', value)
    }
}

/**
 * Class for outputs of action CustomerDeleteCustomer
 * 
 */
class CustomerDeleteCustomerOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomerDeleteCustomerOutputs'
    }

}

Factory.register('altair.crm5.CustomerDeleteCustomer', CustomerDeleteCustomer)
Factory.register('altair.crm5.CustomerDeleteCustomerInputs', CustomerDeleteCustomerInputs)
Factory.register('altair.crm5.CustomerDeleteCustomerOutputs', CustomerDeleteCustomerOutputs)

module.exports = {
    CustomerDeleteCustomer,
    CustomerDeleteCustomerInputs,
    CustomerDeleteCustomerOutputs
}