// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------

const pack = {

        // definitions
         ...require('./CustomerCreateCustomer'),
         ...require('./CustomerDeleteCustomer'),
         ...require('./CustomerGetCustomer'),
         ...require('./CustomerGetAllCustomers'),
         ...require('./CustomerFilterCustomers'),
         ...require('./CustomerSearchCustomer'),
         ...require('./CustomerUpdateCustomer'),
         ...require('./CustomerGetCustomerOrders'),
         ...require('./CustomerCreateCustomerFiles'),
         ...require('./CustomerGetCustomerFiles'),
         ...require('./CustomerCreateCustomerCustomFiles')
}


module.exports = pack;