// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class CustomFileEntityUpdateFile extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new CustomFileEntityUpdateFileInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.CustomFileEntityUpdateFile'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/CustomFileEntity/updateFile'
    }

}

/**
 * Class for inputs of action CustomFileEntityUpdateFile
 * 
 */
class CustomFileEntityUpdateFileInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomFileEntityUpdateFileInputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get id(){
        return this.get('id')
    }
    
    set id(value){
        this.set('id', value)
    }
    /**
     * String arg
     * 
     * @type { string }
     */
    get description(){
        return this.get('description')
    }
    
    set description(value){
        this.set('description', value)
    }
    /**
     * String arg
     * 
     * @type { bool }
     */
    get islock(){
        return this.get('islock')
    }
    
    set islock(value){
        this.set('islock', value)
    }
}

/**
 * Class for outputs of action CustomFileEntityUpdateFile
 * 
 */
class CustomFileEntityUpdateFileOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomFileEntityUpdateFileOutputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get status(){
        return this.get('status')
    }
    
    set status(value){
        this.set('status', value)
    }
}

Factory.register('altair.crm5.CustomFileEntityUpdateFile', CustomFileEntityUpdateFile)
Factory.register('altair.crm5.CustomFileEntityUpdateFileInputs', CustomFileEntityUpdateFileInputs)
Factory.register('altair.crm5.CustomFileEntityUpdateFileOutputs', CustomFileEntityUpdateFileOutputs)

module.exports = {
    CustomFileEntityUpdateFile,
    CustomFileEntityUpdateFileInputs,
    CustomFileEntityUpdateFileOutputs
}