// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class CustomFileEntityDeleteFile extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new CustomFileEntityDeleteFileInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.CustomFileEntityDeleteFile'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/CustomFileEntity/deleteFile'
    }

}

/**
 * Class for inputs of action CustomFileEntityDeleteFile
 * 
 */
class CustomFileEntityDeleteFileInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomFileEntityDeleteFileInputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get id(){
        return this.get('id')
    }
    
    set id(value){
        this.set('id', value)
    }
}

/**
 * Class for outputs of action CustomFileEntityDeleteFile
 * 
 */
class CustomFileEntityDeleteFileOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomFileEntityDeleteFileOutputs'
    }

    /**
     * String arg
     * 
     * @type { string }
     */
    get status(){
        return this.get('status')
    }
    
    set status(value){
        this.set('status', value)
    }
}

Factory.register('altair.crm5.CustomFileEntityDeleteFile', CustomFileEntityDeleteFile)
Factory.register('altair.crm5.CustomFileEntityDeleteFileInputs', CustomFileEntityDeleteFileInputs)
Factory.register('altair.crm5.CustomFileEntityDeleteFileOutputs', CustomFileEntityDeleteFileOutputs)

module.exports = {
    CustomFileEntityDeleteFile,
    CustomFileEntityDeleteFileInputs,
    CustomFileEntityDeleteFileOutputs
}