// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------
//Created from  JsGlobalActionClassTemplate

const UserAction = require('@altair/system').UserAction
const ActionInputs = require('@altair/system').ActionInputs
const ActionOutputs = require('@altair/system').ActionOutputs
const Factory = require('@altair/system').Factory

let srcModule = undefined;

class CustomFileEntityCreateFile extends UserAction{
    constructor({session}){
        super({session})
        this._srcModule = srcModule

        // set inputs
        this.set('inputs', new CustomFileEntityCreateFileInputs(session=session))
        this.set('inline', true)
    }

    /**
     * Content type
     * 
     * @type {string}
     */
    get contentType(){
        return 'altair.crm5.CustomFileEntityCreateFile'
    }

    /**
     * Get relative URL of the action
     */
    get relativeUrl(){
        return '/altair/crm5/CustomFileEntity/createFile'
    }

}

/**
 * Class for inputs of action CustomFileEntityCreateFile
 * 
 */
class CustomFileEntityCreateFileInputs extends ActionInputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomFileEntityCreateFileInputs'
    }

    /**
     * String arg
     * 
     * @type { object }
     */
    get contentRef(){
        return this.get('contentRef')
    }
    
    set contentRef(value){
        this.set('contentRef', value)
    }
    /**
     * String arg
     * 
     * @type { string }
     */
    get description(){
        return this.get('description')
    }
    
    set description(value){
        this.set('description', value)
    }
    /**
     * String arg
     * 
     * @type { bool }
     */
    get islock(){
        return this.get('islock')
    }
    
    set islock(value){
        this.set('islock', value)
    }
    /**
     * String arg
     * 
     * @type { FileEntityRef }
     */
    get fileRef(){
        return this.get('fileRef')
    }
    
    set fileRef(value){
        this.set('fileRef', value)
    }
}

/**
 * Class for outputs of action CustomFileEntityCreateFile
 * 
 */
class CustomFileEntityCreateFileOutputs extends ActionOutputs{

    constructor({session}) {
        super({session})
    }

    /**
     * Property type
     * 
     * @type {string}
     */
    get propertyType(){
        return 'altair.crm5.CustomFileEntityCreateFileOutputs'
    }

    /**
     * String arg
     * 
     * @type { object }
     */
    get file(){
        return this.get('file')
    }
    
    set file(value){
        this.set('file', value)
    }
}

Factory.register('altair.crm5.CustomFileEntityCreateFile', CustomFileEntityCreateFile)
Factory.register('altair.crm5.CustomFileEntityCreateFileInputs', CustomFileEntityCreateFileInputs)
Factory.register('altair.crm5.CustomFileEntityCreateFileOutputs', CustomFileEntityCreateFileOutputs)

module.exports = {
    CustomFileEntityCreateFile,
    CustomFileEntityCreateFileInputs,
    CustomFileEntityCreateFileOutputs
}