// --------------------------------------------------------------------------------
// Autogenerated by Altair One content definition compiler.
// Do not modify this file.
// --------------------------------------------------------------------------------

const pack = {

        // definitions
         ...require('./CustomFileEntityCreateFile'),
         ...require('./CustomFileEntityGetFiles'),
         ...require('./CustomFileEntityUpdateFile'),
         ...require('./CustomFileEntityDeleteFile')
}


module.exports = pack;